FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "raylib-beef"
TargetType = "BeefLib"
StartupObject = "Program"

[Configs.Debug.Win64]
CLibType = "Static"
BeefLibType = "Static"
LibPaths = ["$(ProjectDir)/dist/x64/raylib_static.lib"]

[Configs.Debug.Win32]
BuildKind = "DynamicLib"
CLibType = "None"
LibPaths = ["$(ProjectDir)/dist/x86/raylib_static.lib"]

[Configs.Paranoid.Win32]
BuildKind = "DynamicLib"

[Configs.Paranoid.Win64]
BuildKind = "DynamicLib"

[Configs.Release.Win64]
BuildKind = "StaticLib"
LibPaths = ["$(ProjectDir)/dist/x64/raylib_static.lib"]

[Configs.Release.Win32]
BuildKind = "DynamicLib"
CLibType = "None"
LibPaths = ["$(ProjectDir)/dist/x86/raylib_static.lib"]

[Configs.Test.Win32]
BuildKind = "DynamicLib"

[Configs.Test.Win64]
BuildKind = "DynamicLib"
